# Generated by Django 6.0.3 on 2026-04-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('normal', 'Normal'), ('suspended', 'Suspended')], default='normal', max_length=16),
        ),
    ]
