# Generated by Django 6.0.3 on 2026-04-04 02:38

from django.db import migrations


def sync_existing_user_roles(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.filter(is_superuser=True).update(role='superuser')


def reverse_sync_existing_user_roles(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.filter(role='superuser').update(role='normal')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_is_admin_user_role'),
    ]

    operations = [
        migrations.RunPython(sync_existing_user_roles, reverse_sync_existing_user_roles),
    ]
