# Generated by Django 6.0.3 on 2026-04-04 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.JSONField(blank=True, default=list, help_text='List of community rules (array of strings).'),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['superuser', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(help_text='Unique identifier used in URLs. 2-32 chars: lowercase letters, numbers, underscore. eg. /[name]', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Community name must be 2-32 chars: lowercase letters, numbers, underscore.', regex='^[a-z0-9_]{2,32}$')]),
        ),
    ]
