# Generated by Django 6.0.3 on 2026-04-04 06:50

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fix_admin_log_user_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name_plural': 'Communities'},
        ),
        migrations.AddField(
            model_name='community',
            name='adult_content',
            field=models.BooleanField(default=False, help_text='Whether the community contains adult content. Registered users can access adult communities, hidden from unregistered users.'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.thread_image_upload_path)),
                ('adult_content', models.BooleanField(default=False, help_text='Hide from not logged in users if true.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('platform_violation', 'Platform Rules Violation'), ('community_violation', 'Community Rules Violation'), ('removed_by_user', 'Removed by User'), ('removed_by_mod', 'Removed by Moderator')], default='public', help_text='Moderation status of the thread.', max_length=32)),
                ('removal_reason', models.TextField(blank=True, help_text='Reason for removal by moderator or user.')),
                ('is_locked', models.BooleanField(default=False, help_text='If true, no new replies can be added.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('author', models.ForeignKey(blank=True, help_text='User who created the thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(help_text='Community this thread belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='api.community')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('platform_violation', 'Platform Rules Violation'), ('community_violation', 'Community Rules Violation'), ('removed_by_user', 'Removed by User'), ('removed_by_mod', 'Removed by Moderator')], default='public', help_text='Moderation status of the reply.', max_length=32)),
                ('removal_reason', models.TextField(blank=True, help_text='Reason for removal by moderator or user.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('is_edited', models.BooleanField(default=False, help_text='True if reply was edited after creation.')),
                ('author', models.ForeignKey(blank=True, help_text='User who wrote the reply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(help_text='Thread this reply belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.thread')),
            ],
            options={
                'verbose_name_plural': 'Replies',
                'ordering': ['created_at'],
            },
        ),
    ]
