# Generated by Django 6.0.3 on 2026-04-05

import re
from django.db import migrations, models


def _build_schema_name(community_name):
    normalized = re.sub(r'[^a-z0-9_]', '_', (community_name or '').lower()).strip('_')
    normalized = normalized or 'community'
    return f"community_{normalized}"[:63]


def _provision_forum_storage(connection, schema_name, community_table, user_table):
    qn = connection.ops.quote_name
    schema = qn(schema_name)
    thread_table = f"{schema}.{qn('threads')}"
    reply_table = f"{schema}.{qn('replies')}"

    with connection.cursor() as cursor:
        cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {thread_table} (
                id BIGSERIAL PRIMARY KEY,
                community_id BIGINT NOT NULL REFERENCES {community_table}(id) ON DELETE CASCADE,
                author_id BIGINT NULL REFERENCES {user_table}(id) ON DELETE SET NULL,
                title VARCHAR(200) NOT NULL DEFAULT '',
                description TEXT NOT NULL DEFAULT '',
                image VARCHAR(255) NULL,
                adult_content BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                last_activity TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                status VARCHAR(32) NOT NULL DEFAULT 'public',
                removal_reason TEXT NOT NULL DEFAULT '',
                is_locked BOOLEAN NOT NULL DEFAULT FALSE,
                is_deleted BOOLEAN NOT NULL DEFAULT FALSE
            )
            """
        )
        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {reply_table} (
                id BIGSERIAL PRIMARY KEY,
                thread_id BIGINT NOT NULL REFERENCES {thread_table}(id) ON DELETE CASCADE,
                author_id BIGINT NULL REFERENCES {user_table}(id) ON DELETE SET NULL,
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                status VARCHAR(32) NOT NULL DEFAULT 'public',
                removal_reason TEXT NOT NULL DEFAULT '',
                is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                is_edited BOOLEAN NOT NULL DEFAULT FALSE
            )
            """
        )
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS {qn('threads_community_created_idx')} ON {thread_table} (community_id, created_at DESC)"
        )
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS {qn('replies_thread_created_idx')} ON {reply_table} (thread_id, created_at ASC)"
        )


def backfill_schema_and_storage(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return

    Community = apps.get_model('api', 'Community')
    User = apps.get_model('api', 'User')

    community_table = connection.ops.quote_name(Community._meta.db_table)
    user_table = connection.ops.quote_name(User._meta.db_table)

    used_schema_names = set(
        Community.objects.exclude(schema_name__isnull=True)
        .exclude(schema_name='')
        .values_list('schema_name', flat=True)
    )

    for community in Community.objects.order_by('id'):
        schema_name = (community.schema_name or '').strip()

        if not schema_name:
            base_name = _build_schema_name(community.name)
            schema_name = base_name
            suffix = 1
            while schema_name in used_schema_names:
                suffix_str = f"_{suffix}"
                schema_name = f"{base_name[:63 - len(suffix_str)]}{suffix_str}"
                suffix += 1

            community.schema_name = schema_name
            community.save(update_fields=['schema_name'])

        used_schema_names.add(schema_name)
        _provision_forum_storage(connection, schema_name, community_table, user_table)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_community_options_community_adult_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='schema_name',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='PostgreSQL schema used for this community local forum tables.',
                max_length=63,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_schema_and_storage, noop_reverse),
    ]
