# Generated by Django 6.0.3 on 2026-04-05

from django.db import migrations


def move_thread_reply_to_community_schemas(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return

    Community = apps.get_model('api', 'Community')
    qn = connection.ops.quote_name

    public_thread_table = qn('api_thread')
    public_reply_table = qn('api_reply')

    with connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass('public.api_thread') IS NOT NULL")
        thread_exists = cursor.fetchone()[0]
        cursor.execute("SELECT to_regclass('public.api_reply') IS NOT NULL")
        reply_exists = cursor.fetchone()[0]

        if not thread_exists:
            return

        communities = Community.objects.exclude(schema_name__isnull=True).exclude(schema_name='')

        for community in communities.iterator():
            schema = qn(community.schema_name)
            schema_thread_table = f"{schema}.{qn('threads')}"
            schema_reply_table = f"{schema}.{qn('replies')}"

            cursor.execute(
                f"""
                INSERT INTO {schema_thread_table} (
                    id,
                    community_id,
                    author_id,
                    title,
                    description,
                    image,
                    adult_content,
                    created_at,
                    updated_at,
                    last_activity,
                    status,
                    removal_reason,
                    is_locked,
                    is_deleted
                )
                SELECT
                    t.id,
                    t.community_id,
                    t.author_id,
                    t.title,
                    t.description,
                    t.image,
                    t.adult_content,
                    t.created_at,
                    t.updated_at,
                    t.last_activity,
                    t.status,
                    t.removal_reason,
                    t.is_locked,
                    t.is_deleted
                FROM {public_thread_table} t
                WHERE t.community_id = %s
                ON CONFLICT (id) DO NOTHING
                """,
                [community.id],
            )

            if reply_exists:
                cursor.execute(
                    f"""
                    INSERT INTO {schema_reply_table} (
                        id,
                        thread_id,
                        author_id,
                        content,
                        created_at,
                        updated_at,
                        status,
                        removal_reason,
                        is_deleted,
                        is_edited
                    )
                    SELECT
                        r.id,
                        r.thread_id,
                        r.author_id,
                        r.content,
                        r.created_at,
                        r.updated_at,
                        r.status,
                        r.removal_reason,
                        r.is_deleted,
                        r.is_edited
                    FROM {public_reply_table} r
                    INNER JOIN {public_thread_table} t ON t.id = r.thread_id
                    WHERE t.community_id = %s
                    ON CONFLICT (id) DO NOTHING
                    """,
                    [community.id],
                )

            cursor.execute(
                f"""
                SELECT setval(
                    pg_get_serial_sequence('{community.schema_name}.threads', 'id'),
                    COALESCE((SELECT MAX(id) FROM {schema_thread_table}), 1),
                    (SELECT COUNT(*) > 0 FROM {schema_thread_table})
                )
                """
            )

            if reply_exists:
                cursor.execute(
                    f"""
                    SELECT setval(
                        pg_get_serial_sequence('{community.schema_name}.replies', 'id'),
                        COALESCE((SELECT MAX(id) FROM {schema_reply_table}), 1),
                        (SELECT COUNT(*) > 0 FROM {schema_reply_table})
                    )
                    """
                )

        if reply_exists:
            cursor.execute(f"DROP TABLE IF EXISTS {public_reply_table}")
        cursor.execute(f"DROP TABLE IF EXISTS {public_thread_table}")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_community_schema_name_and_forum_storage'),
    ]

    operations = [
        migrations.RunPython(move_thread_reply_to_community_schemas, noop_reverse),
    ]
